package View;

import JDBC.AnamneseDao;
import JDBC.ClientesDao;
import JDBC.ConnectionFactory;
import JDBC.VistaDorsalDao;
import JDBC.VistaPlantarDao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;

import java.util.Date;
import java.util.List;
import javabeans.Anamnese;
import javabeans.Clientes;
import javabeans.VistaDorsal;
import javabeans.VistaPlantar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
//import net.proteanit.sql.DbUtils;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BRUNO
 */
public class Pesquisar extends javax.swing.JFrame {




    /**
     * Creates new form Pesquisar
     */
    public void Listar() {
        try {
            //1 passo - Executar o Select

            ClientesDao dao = new ClientesDao();
            List<Clientes> listadeclientes = dao.listarclientes();

            //2 passo - colocar os dados na tabela 
            DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
            modelo.setNumRows(0);

            for (Clientes cli : listadeclientes) {
                modelo.addRow(new Object[]{
                    cli.getId(),
                    cli.getNome(),
                    cli.getCpf(),
                    cli.getRg(),
                    cli.getNascimento(),
                    cli.getCep(),
                    cli.getEndereco(),
                    cli.getNumero(),
                    cli.getUf(),
                    cli.getBairro(),
                    cli.getCidade(),
                    cli.getTelefone(),
                    cli.getCelular(),
                    cli.getEmail(),
                    cli.getObservacao()

                });

            }

        } catch (Exception e) {
        }

    }

    public Pesquisar() {
        initComponents();
    }

    public void tela(TelaCadastroCliente telacadastro) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        novoCadastro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        abrir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta Cliente"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );

        jLabel1.setText("Pesquisar Cliente Cadastrado");

        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome do Cliente", "CPF", "RG", "DataNascimento", "CEP", "Endereço", "N°", "UF", "Bairro", "Cidade", "Telefone", "Celular", "Email", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        tabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        novoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.png"))); // NOI18N
        novoCadastro.setText("Novo");
        novoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoCadastroActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });

        abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/folder-35945_960_720.png"))); // NOI18N
        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1044, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(novoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(novoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Listando dados na tabela 
        
    }//GEN-LAST:event_formWindowOpened

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        txtIdCliente.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
       txtPesquisar.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());

        

    }//GEN-LAST:event_tabelaMouseClicked

    private void novoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoCadastroActionPerformed
 
        //variabel que vai receber o proximo id de cliente a ser cadastrado
        Integer proximo_id = null;
        
        Clientes clientes = new Clientes();
        
        //objeto da classe DAO para acessar metodo de verificar proximo id
        ClientesDao cDAO = new ClientesDao();
        //setando o proximo id na variavel
        proximo_id = cDAO.pegarProximoIdParaCadastrar();
        
        
        TelaCadastroCliente telacadastro = new TelaCadastroCliente(clientes);
        telacadastro.txtId.setText(""+proximo_id);
        telacadastro.setVisible(true);
        

    }//GEN-LAST:event_novoCadastroActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

          Clientes clientes = new Clientes();
          Anamnese anamnese = new Anamnese();
             ClientesDao clientesdao = new ClientesDao();
             AnamneseDao anamnesedao = new AnamneseDao();
             VistaPlantar vista = new VistaPlantar();
             VistaPlantarDao vistadao = new VistaPlantarDao();
             VistaDorsalDao vistadorsaldao = new VistaDorsalDao();
             VistaDorsal vistadorsal = new VistaDorsal();
       Date data = new Date();
      SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
      String nascimento = formatador.format(data);
   
          
        

    
           vistadorsal.setIdClienteVd(Integer.parseInt(txtIdCliente.getText()));
           vista.setIdClienteVp(Integer.parseInt(txtIdCliente.getText()));
           anamnese.setIdCliente(Integer.parseInt(txtIdCliente.getText()));
           clientes.setId(Integer.parseInt(txtIdCliente.getText()));
           
        
       
      try{     
        vistadorsaldao.excluirVistaDorsal(vistadorsal);
        vistadao.excluirVistaPlantar(vista);
        anamnesedao.excluirClienteAname(anamnese);
      clientesdao.excluirCliente(clientes);
             JOptionPane.showMessageDialog(null, "Dados excluidos com sucesso!");
             
         } catch (Exception e) {
          e.printStackTrace();
         JOptionPane.showMessageDialog(null, "Erro excluir");
        }
  
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tabelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaKeyReleased
        
    }//GEN-LAST:event_tabelaKeyReleased

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
       //o evento abaixo é do tipo "enquanto for digitando"
        // chamar metodo pesquisar clientes
 pesquisar_cliente();
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
   

    }//GEN-LAST:event_btnExcluirMouseClicked

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
         
 //ao clicar no cliente da lista abre outra janela com os dados do cliente
             Clientes clientes = new Clientes();
             AnamneseDao aDao = new AnamneseDao();
           Anamnese a = new Anamnese();
           
        clientes.setId(Integer.parseInt(String.valueOf(tabela.getValueAt(tabela.getSelectedRow(),0 ))));
        clientes.setNome(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
        clientes.setCpf(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
        clientes.setRg(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
        clientes.setNascimento(tabela.getValueAt(tabela.getSelectedRow(), 4).toString());
        clientes.setCep(tabela.getValueAt(tabela.getSelectedRow(), 5).toString());
        clientes.setEndereco(tabela.getValueAt(tabela.getSelectedRow(), 6).toString());
        clientes.setNumero(Integer.parseInt(String.valueOf(tabela.getValueAt(tabela.getSelectedRow(),7 ))));
        clientes.setUf(tabela.getValueAt(tabela.getSelectedRow(), 8).toString());
        clientes.setBairro(tabela.getValueAt(tabela.getSelectedRow(), 9).toString());
        clientes.setCidade(tabela.getValueAt(tabela.getSelectedRow(), 10).toString());
        clientes.setTelefone(tabela.getValueAt(tabela.getSelectedRow(), 11).toString());
        clientes.setCelular(tabela.getValueAt(tabela.getSelectedRow(), 12).toString());
        clientes.setEmail(tabela.getValueAt(tabela.getSelectedRow(), 13).toString());
        clientes.setObservacao(tabela.getValueAt(tabela.getSelectedRow(), 14).toString());
            
        
       

        TelaCadastroCliente telacadastro = new TelaCadastroCliente(clientes);
        telacadastro.setVisible(true);
    }//GEN-LAST:event_abrirActionPerformed

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Listar();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesquisar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrir;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton novoCadastro;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables

//consulta avancada de pesquisar clientes
    private Connection conecta;
   



private void pesquisar_cliente() {
    try {
this.conecta = new ConnectionFactory().getConnection();
//1 passo - criar vetor que vai armazenas os registros do banco 
        
      //2 passo - criar o comando sql 
      String cmdsql="SELECT * FROM clientes where nome like?";
      

       PreparedStatement pstm = conecta.prepareStatement(cmdsql);
       //3 passo - Guardo o resultado do select dentro do obejeto rs(resultSet)
        pstm.setString(1, txtPesquisar.getText() + "%");
        ResultSet rs = pstm.executeQuery();

            tabela.setModel(DbUtils.resultSetToTableModel(rs));
       //4 passo - Enquanto houver registros (resultado do select)guarde o registo na lista 

        
    } catch (Exception erro) {
      erro.printStackTrace();
      throw new RuntimeException(erro);
    }
 



    }


 
}
